# Generated by Django 5.1.6 on 2025-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_photo_3_pet_photo_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='photo_4',
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
