# Generated by Django 5.1.6 on 2025-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_photo_3_pet_photo_4_pet_photo_5_pet_photo_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='location',
        ),
        migrations.AddField(
            model_name='pet',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
