# Generated by Django 5.1.6 on 2025-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_pet_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
