# Generated by Django 5.1.6 on 2025-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_pet_status_pet_user_alter_pet_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
