# Generated by Django 5.1.6 on 2025-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelterapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelterapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shelterapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shelterapplication',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shelterapplication',
            name='shelter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
