# Generated by Django 5.1.6 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pet_experience',
            field=models.CharField(choices=[('beginner', 'Beginner - No experience'), ('some_experience', 'Some experience'), ('experienced', 'Experienced'), ('expert', 'Expert - Have owned many pets')], default='beginner', max_length=20),
        ),
    ]
